In [1]:
import numpy as np
import torch as T
from dgamod import *

In [2]:
n = 10
iterations = 1 
dt = 0.15
tolerance = 0.95
reward_decay = 0.95
action_sequences = np.random.randint(low=0, high=16, size=[iterations,50])
actions = actions_zhang(100,n)
print(action_sequences)
props = gen_props(actions,n,dt,test=True)

[[13 11 11 14 13  9  1  2  7 13  8  5 13 13  7 13 12 13  9  5  3  5  9 10
   9 12  8 12  2 10  4  4  8  5  3  1 15 10  0 10  1 14  8  9 12  1 14  1
   6  9]]
Eigenstate Propagation: correct


In [3]:
reward_based_fitness_gpu(action_sequences, props, tolerance, reward_decay)

tensor([[0.0000e+00, 8.7773e-28, 2.4445e-22, 1.6383e-19, 2.0417e-16, 1.3348e-15,
         9.6854e-16, 2.0866e-12, 7.5405e-11, 8.9774e-10, 3.9110e-09, 9.8625e-09,
         2.5642e-08, 5.3890e-08, 8.9484e-08, 2.9545e-07, 9.8003e-07, 9.3714e-07,
         1.8094e-07, 1.7162e-07, 1.5444e-06, 7.9423e-06, 3.0003e-05, 3.3493e-05,
         3.0219e-05, 2.9747e-05, 3.2078e-05, 2.4028e-05, 2.1229e-05, 1.4468e-05,
         1.3907e-05, 3.8116e-05, 8.8664e-05, 1.6474e-04, 2.2087e-04, 2.0843e-04,
         1.4851e-04, 1.2920e-04, 1.0780e-04, 3.6164e-05, 6.2256e-05, 3.8918e-04,
         1.4969e-03, 3.4245e-03, 3.4803e-03, 3.5426e-03, 5.8768e-03, 7.9456e-03,
         9.3513e-03, 9.9533e-03, 9.8873e-03]], device='cuda:0',
       dtype=torch.float64)
tensor([0.0521], device='cuda:0', dtype=torch.float64)


array([0.05214316])

In [4]:
print(fidelity(action_sequences[0,:], props))

0.00995331544754617


In [5]:
print(reward_based_fitness(action_sequences[0,:], props, tolerance, reward_decay))

0.05214315702794536
